cluster_id: 'cluster'
instance_id: 1
interface: 'eth0'
port_tcp: 6223
port_udp: 6224
mode: 'leader'
weight: 10
timeout: '5s'

check_script: 'scripts/check.sh'
check_interval: '5s'
check_retries: 5
check_timeout: '10s'

run_script: 'scripts/run.sh'
run_timeout: '10s'

stop_script: 'scripts/stop.sh'
stop_timeout: '10s'